### ISSUE TITLE
recovery revamp

### ISSUE THREAD

**Issue by spacejam** [spacejam/sled#155]
Recovery is really nasty right now, after the log-structured architectural overhaul. `SegmentAccountant` in particular has an overly confusing recovery implementation.

1. generate set of (Lsn, LogID) on startup
1. prune them if the tip is not contiguous with backrefs
1. generate a new snapshot from the last snapshot and the log
1. initialize the `SegmentAccountant`
1. initialize the `PageCache`
1. start the `Tree` with the recovered state

- [x] (#157) refactor `SegmentAccountant`
- [x] (#169) refactor snapshot generation
- [x] (#171) add tests to see if the snapshot + log scan results in the same recovered snapshot as just a log scan 
- [x] (#190) add `SegmentAccountant` + recovery + segment lifecycle quickcheck tests
