### ISSUE TITLE
benchmark tool

### ISSUE THREAD

**Issue by spacejam** [spacejam/sled#58]
- [x] read in arguments https://github.com/spacejam/rsdb/issues/55
- [x] implement simple N threads, set/get/cas/del ops https://github.com/spacejam/rsdb/issues/56
- [x] measure throughput and latency https://github.com/spacejam/rsdb/issues/57
- [ ] implement the advanced options that arguments were created for
- [ ] implement zipfian key distributions to target some hot keys more than others, simulating more realistic popularity among data.

**Comment by spacejam** [comment]
closing for now, since other areas need more attention
